# Generated by Django 4.2.3 on 2024-01-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus_TB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=40)),
                ("bus_name", models.CharField(max_length=100)),
                ("bus_number", models.CharField(max_length=100)),
                ("bording_point", models.CharField(max_length=100)),
                ("droppinging_point", models.CharField(max_length=100)),
                ("start_time", models.CharField(max_length=100)),
                ("end_time", models.CharField(max_length=100)),
                ("fare", models.CharField(max_length=100)),
                ("total_seats", models.CharField(max_length=100)),
                ("available_seats", models.CharField(max_length=100)),
                ("img", models.ImageField(null=True, upload_to="images/")),
                ("statuz", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry_Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Subject", models.CharField(max_length=500)),
                ("Message", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="LogIN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User_Registartion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passenger_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Gender", models.CharField(max_length=100)),
                ("Age", models.CharField(max_length=100)),
                ("today", models.CharField(max_length=100)),
                ("statuz", models.CharField(max_length=100)),
                ("seat_no", models.CharField(max_length=100)),
                ("seat", models.CharField(max_length=100)),
                (
                    "busid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.bus_tb"
                    ),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="login_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
            ),
        ),
        migrations.CreateModel(
            name="Bus_company_Registartion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                ("statuz", models.CharField(max_length=30)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booked_seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_seat", models.CharField(max_length=100)),
                ("seat_no", models.CharField(max_length=100)),
                ("total_fare", models.CharField(max_length=100)),
                ("today", models.CharField(max_length=100)),
                (
                    "busid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.bus_tb"
                    ),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin_Registartion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
    ]
