# Generated by Django 4.2.3 on 2023-10-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus_TB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=40)),
                ("bus_count", models.CharField(max_length=30)),
                ("bus_name", models.CharField(max_length=30)),
                ("bus_number", models.CharField(max_length=30)),
                ("route", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="LogIN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="User_Registartion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bus_Owner_Registartion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                ("statuz", models.CharField(max_length=30)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
    ]
