# Generated by Django 4.2.3 on 2023-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0002_bus_tb_img"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bus_Owner_Registartion",
            new_name="Bus_company_Registartion",
        ),
        migrations.RenameField(
            model_name="bus_tb",
            old_name="owner_name",
            new_name="company_name",
        ),
        migrations.RemoveField(
            model_name="bus_tb",
            name="bus_count",
        ),
        migrations.RemoveField(
            model_name="bus_tb",
            name="route",
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="available_dates",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="bording_point",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="droppinging_point",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="end_time",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="fare",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="start_time",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus_tb",
            name="total_seats",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bus_tb",
            name="bus_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bus_tb",
            name="bus_number",
            field=models.CharField(max_length=100),
        ),
    ]
