# Generated by Django 4.2.3 on 2023-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0004_bus_tb_login_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus_tb",
            name="statuz",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
