# Generated by Django 4.2.3 on 2023-10-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0005_bus_tb_statuz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_tb",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
