# Generated by Django 4.2.3 on 2023-11-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0006_alter_bus_tb_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus_tb",
            name="available_seats",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
