# Generated by Django 4.2.3 on 2023-11-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0007_bus_tb_available_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_tb",
            name="img",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
