# Generated by Django 4.2.3 on 2023-11-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0008_alter_bus_tb_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booked_seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_seat", models.CharField(max_length=100)),
                ("seat_no", models.CharField(max_length=100)),
                ("total_fare", models.CharField(max_length=100)),
                ("today", models.CharField(max_length=100)),
                (
                    "busid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.bus_tb"
                    ),
                ),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
    ]
