# Generated by Django 4.2.3 on 2023-11-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0009_booked_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booked_seat",
            name="today",
            field=models.DateField(max_length=100),
        ),
    ]
