# Generated by Django 4.2.3 on 2023-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0010_alter_booked_seat_today"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booked_seat",
            name="today",
            field=models.CharField(max_length=100),
        ),
    ]
