# Generated by Django 4.2.3 on 2023-11-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0011_alter_booked_seat_today"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Gender", models.CharField(max_length=100)),
                ("Age", models.CharField(max_length=100)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
    ]
