# Generated by Django 4.2.3 on 2023-11-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0012_passenger_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger_details",
            name="today",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
