# Generated by Django 4.2.3 on 2023-11-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0013_passenger_details_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger_details",
            name="statuz",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
