# Generated by Django 4.2.3 on 2023-12-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0015_enquiry_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin_Registartion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tripbus.login"
                    ),
                ),
            ],
        ),
    ]
