# Generated by Django 4.2.3 on 2023-12-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tripbus", "0016_admin_registartion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus_tb",
            name="available_dates",
        ),
    ]
